function [fitresult, gof] = FitLknee(t, Lknee)
%CREATEFIT(T,LKNEE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: Lknee
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 22:34:39


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, Lknee );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [31.2288753570344 0.020943951023932 3.07814887613572 21.5410535986387 0.167551608191456 2.09360252830843 21.6224969057323 0.0837758040957278 -0.0653198324063915 12.6629909678245 0.0418879020478639 -1.63133938295194 7.5303400433935 0.251327412287183 -2.94147342533609 2.41527771646703 0.20943951023932 -2.03692369602561 2.3503073940264 0.125663706143592 3.08633299667004 1.47222569300292 0.418879020478639 -2.80674285002441];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Lknee vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't', 'Interpreter', 'none' );
ylabel( 'Lknee', 'Interpreter', 'none' );
grid on


