function [fitresult, gof] = FitLhip(t, Lhip)
%CREATEFIT(T,LHIP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: Lhip
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 22:33:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, Lhip );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [20.5632853133912 0.0837758040957278 1.79074439913918 7.07096994917673 0.167551608191456 -1.66755672972834 2.90690924347254 0.251327412287183 0.209555837443217 1.70154894569622 0.020943951023932 -2.53858982909336 1.11728865884423 0.125663706143592 -1.41719946138906 0.577401915880797 0.20943951023932 0.371913894222301 0.575610788969287 0.418879020478639 -0.191781918997265 0.442326355496257 0.502654824574367 1.27501820169359];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Lhip vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't', 'Interpreter', 'none' );
ylabel( 'Lhip', 'Interpreter', 'none' );
grid on


