function [fitresult, gof] = FitLankle(t, Lankle)
%CREATEFIT(T,LANKLE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: Lankle
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 22:35:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, Lankle );

% Set up fittype and options.
ft = fittype( 'sin7' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [6.09768230288982 0.0837758040957278 -1.21627345365709 3.00638326113666 0.251327412287183 -1.44751189088485 2.18956609517344 0.167551608191456 2.90016547189605 1.84371159277626 0.335103216382911 0.987871523403161 1.27350917776018 0.020943951023932 -0.317137696269647 1.23393025977926 0.418879020478639 2.66072194326053 0.644839923184842 0.586430628670095 1.6202007391331];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Lankle vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't', 'Interpreter', 'none' );
ylabel( 'Lankle', 'Interpreter', 'none' );
grid on


