function [fitresult, gof] = FitRhip(t, Rhip)
%CREATEFIT(T,RHIP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: Rhip
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 23:03:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, Rhip );

% Set up fittype and options.
ft = fittype( 'sin3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [23.1296830522398 0.0837758040957278 -1.43047685532284 6.75589692173411 0.167551608191456 -1.68495954877819 2.97927170500671 0.251327412287183 2.83841523602724];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Rhip vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't', 'Interpreter', 'none' );
ylabel( 'Rhip', 'Interpreter', 'none' );
grid on


