function [fitresult, gof] = FitRankle(t, Rankle)
%CREATEFIT(T,RANKLE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: Rankle
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 22:32:20


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, Rankle );

% Set up fittype and options.
ft = fittype( 'sin7' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [6.3889319451321 0.020943951023932 -0.122276340767176 6.21206805617132 0.0837758040957278 2.15965017418634 3.40354419633186 0.251327412287183 1.51826407286665 3.09714851987051 0.167551608191456 2.80805579552352 3.42916112377 0.0418879020478639 1.48821860876356 1.60797535385651 0.335103216382911 0.918847415023697 1.42138340847524 0.418879020478639 -0.387799700916921];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Rankle vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't', 'Interpreter', 'none' );
ylabel( 'Rankle', 'Interpreter', 'none' );
grid on


