function [fitresult, gof] = FitRknee(t, Rknee)
%CREATEFIT(T,RKNEE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: Rknee
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2022 22:27:51


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, Rknee );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [35.9241269343112 0.020943951023932 -3.10676851537756 21.1672779041042 0.167551608191456 2.00692339474308 21.1234508554176 0.0837758040957278 -3.00287294092496 15.3666667030289 0.0418879020478639 -1.51514023972667 8.03928631917688 0.251327412287183 -0.235485920597693 2.11806639868012 0.20943951023932 -1.16424091108685 1.87262261601077 0.335103216382911 2.49309168887311 1.60197028792575 0.418879020478639 -0.255152906747605];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Rknee vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't', 'Interpreter', 'none' );
ylabel( 'Rknee', 'Interpreter', 'none' );
grid on


